name: Vercel Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "apps/**"
      - "packages/shared/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-web-preview:
    if: ${{ github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || (github.event.pull_request.draft == false && github.event.pull_request.head.repo.fork == false)) }}
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "preview"
      flags: ""
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_TAIKOPROOFS }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}

  deploy-api-preview:
    if: ${{ github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || (github.event.pull_request.draft == false && github.event.pull_request.head.repo.fork == false)) }}
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "preview"
      flags: ""
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_TAIKOPROOFS_API }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
